import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Navigation from "@/components/Navigation";
import { 
  Brain, 
  Target, 
  Zap, 
  TrendingUp, 
  Users, 
  Award,
  ArrowRight,
  CheckCircle,
  Sparkles
} from "lucide-react";

const Home = () => {
  const features = [
    {
      icon: Brain,
      title: "AI-Powered Learning",
      description: "Personalized learning paths generated by advanced AI algorithms tailored to your career goals."
    },
    {
      icon: Target,
      title: "Smart Job Matching",
      description: "ML-driven cosine similarity matching connects your skills with real job requirements."
    },
    {
      icon: Zap,
      title: "Knowledge Reinforcement",
      description: "Ebbinghaus Forgetting Curve implementation ensures long-term retention of learned concepts."
    },
    {
      icon: TrendingUp,
      title: "Progress Analytics",
      description: "Comprehensive behavioral analytics track your learning journey and predict success."
    }
  ];

  const stats = [
    { number: "95%", label: "Placement Success Rate" },
    { number: "50K+", label: "Students Trained" },
    { number: "500+", label: "Partner Companies" },
    { number: "24/7", label: "AI Support" }
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 hero-gradient opacity-5"></div>
        <div className="relative max-w-7xl mx-auto px-4 py-20 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="flex justify-center mb-6">
              <div className="w-20 h-20 hero-gradient rounded-2xl flex items-center justify-center ai-pulse">
                <Brain className="w-12 h-12 text-white" />
              </div>
            </div>
            <h1 className="text-5xl md:text-6xl font-bold mb-6">
              <span className="text-gradient">LearnSphere</span>
              <br />
              <span className="text-foreground">AI Career Accelerator</span>
            </h1>
            <p className="text-xl text-muted-foreground mb-8 max-w-3xl mx-auto">
              Transform your B.Tech journey with AI-powered personalized learning, ML-driven job matching, 
              and data science insights that guarantee placement readiness.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/dashboard">
                <Button size="lg" className="hero-gradient text-white shadow-primary px-8 py-3">
                  Start Learning Journey
                  <ArrowRight className="ml-2 w-5 h-5" />
                </Button>
              </Link>
              <Link to="/roadmap">
                <Button size="lg" variant="outline" className="px-8 py-3">
                  View AI Roadmap
                  <Sparkles className="ml-2 w-5 h-5" />
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="text-4xl font-bold text-gradient mb-2 stats-counter">
                  {stat.number}
                </div>
                <div className="text-muted-foreground">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">
              Powered by <span className="text-gradient">Advanced AI & ML</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Our platform combines cutting-edge technology with proven learning science 
              to accelerate your career success.
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="learning-card p-6 text-center group">
                <div className="w-16 h-16 hero-gradient rounded-xl flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform">
                  <feature.icon className="w-8 h-8 text-white" />
                </div>
                <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.description}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Your Learning Journey</h2>
            <p className="text-xl text-muted-foreground">
              From knowledge seeding to placement success in 4 simple steps
            </p>
          </div>
          <div className="grid md:grid-cols-4 gap-8">
            {[
              {
                step: "01",
                title: "Knowledge Seeding",
                description: "Register and initialize your personal knowledge graph with chosen interests"
              },
              {
                step: "02", 
                title: "AI Learning Path",
                description: "Get personalized roadmaps and course recommendations powered by AI"
              },
              {
                step: "03",
                title: "Skill Development", 
                description: "Learn through interactive modules with forgetting curve reinforcement"
              },
              {
                step: "04",
                title: "Job Readiness",
                description: "ML-powered job matching provides placement readiness scores"
              }
            ].map((item, index) => (
              <div key={index} className="text-center">
                <div className="w-16 h-16 hero-gradient rounded-full flex items-center justify-center mx-auto mb-4 text-white font-bold text-xl">
                  {item.step}
                </div>
                <h3 className="text-xl font-semibold mb-3">{item.title}</h3>
                <p className="text-muted-foreground">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <Card className="learning-card p-12 hero-gradient text-white relative overflow-hidden">
            <div className="absolute inset-0 bg-black/10"></div>
            <div className="relative">
              <Award className="w-16 h-16 mx-auto mb-6 ai-pulse" />
              <h2 className="text-4xl font-bold mb-4">Ready to Accelerate Your Career?</h2>
              <p className="text-xl text-white/90 mb-8">
                Join thousands of B.Tech students who've transformed their placement prospects with AI-powered learning
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link to="/dashboard">
                  <Button size="lg" variant="secondary" className="px-8 py-3">
                    Start Free Trial
                    <CheckCircle className="ml-2 w-5 h-5" />
                  </Button>
                </Link>
                <Link to="/courses">
                  <Button size="lg" variant="outline" className="px-8 py-3 border-white text-white hover:bg-white/10">
                    Explore Courses
                  </Button>
                </Link>
              </div>
            </div>
          </Card>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 border-t border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <div className="w-8 h-8 hero-gradient rounded-lg flex items-center justify-center">
                <Brain className="w-5 h-5 text-white" />
              </div>
              <span className="text-xl font-bold text-gradient">LearnSphere</span>
            </div>
            <div className="text-muted-foreground text-center md:text-right">
              <p>© 2024 LearnSphere. AI-Powered Career Acceleration Platform.</p>
              <p className="text-sm mt-1">Built with React, TypeScript, and Advanced ML</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;