// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dikgfttqroykuekgizye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpa2dmdHRxcm95a3Vla2dpenllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjA0MTQsImV4cCI6MjA3Mjk5NjQxNH0.P6KxaB2MdcUsipI1Yj0F1oiy2gey7mmmBd9KDS9FcGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});